package broj.gui;

import java.util.*;
import javax.swing.*;

public class Screen extends javax.swing.JFrame {

    private final int X = 50;
    private Random rand = new Random();

    private boolean set;
    private boolean thread_run;
    private boolean stop_all = false;

    private Thread t1;

    private int target;
    private ArrayList<Integer> numbers = new ArrayList<>();

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        restart();
    }

    public void restart() {
        thread_run = true;
        set = false;

        numbers.clear();

        lab1.setText(" ");
        lab2.setText(" ");
        lab3.setText(" ");
        lab4.setText(" ");
        lab5.setText(" ");
        lab6.setText(" ");
        lab7.setText(" ");
        lab8.setText(" ");
        lab9.setText(" ");

        t1 = new Thread() {
            public void run() {
                initialize(this);
            }
        };
        t1.start();
    }

    public void initialize(Thread t) {
        countdown(lab1, t, 0);
        countdown(lab2, t, 0);
        countdown(lab3, t, 0);
        countdown(lab4, t, 1);
        countdown(lab5, t, 1);
        countdown(lab6, t, 1);
        countdown(lab7, t, 1);
        countdown(lab8, t, 10);
        countdown(lab9, t, 25);

        if (!t.isInterrupted()) {
            target = Integer.parseInt(lab1.getText()) * 100
                    + Integer.parseInt(lab2.getText()) * 10
                    + Integer.parseInt(lab3.getText());

            System.out.println(target);

            numbers.add(Integer.parseInt(lab4.getText()));
            numbers.add(Integer.parseInt(lab5.getText()));
            numbers.add(Integer.parseInt(lab6.getText()));
            numbers.add(Integer.parseInt(lab7.getText()));
            numbers.add(Integer.parseInt(lab8.getText()));
            numbers.add(Integer.parseInt(lab9.getText()));

            for (int n : numbers) {
                System.out.print(n + " ");
            }
            System.out.println("");
        }
    }

    public void countdown(JLabel lab, Thread t, int mode) {
        int i = mode;
        if (!t.isInterrupted()) {
            do {
                if (mode == 0) {
                    i = rand.nextInt(10);
                } else if (mode == 1) {
                    i = rand.nextInt(9) + 1;
                } else if (mode == 10) {
                    i = 5 * (rand.nextInt(3) + 2);
                } else {
                    i = 25 * (rand.nextInt(4) + 1);
                }
                lab.setText("" + i);
                try {
                    t.sleep(X);
                } catch (InterruptedException e) {
                    //ignore exception
                    System.out.println("x");
                    t.interrupt();
                }
            } while (!set && thread_run && !t.isInterrupted());
        }

        if (!stop_all) {
            set = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        _stop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lab7 = new javax.swing.JLabel();
        lab5 = new javax.swing.JLabel();
        lab6 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab8 = new javax.swing.JLabel();
        lab9 = new javax.swing.JLabel();
        _restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 155, 243));
        setForeground(new java.awt.Color(0, 153, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        _stop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _stop.setText("STOP");
        _stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _stopActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        lab7.setBackground(new java.awt.Color(255, 51, 51));
        lab7.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab7.setForeground(new java.awt.Color(255, 255, 255));
        lab7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab7.setText("0");
        lab7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lab5.setBackground(new java.awt.Color(255, 51, 51));
        lab5.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab5.setForeground(new java.awt.Color(255, 255, 255));
        lab5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab5.setText("0");
        lab5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lab6.setBackground(new java.awt.Color(255, 51, 51));
        lab6.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab6.setForeground(new java.awt.Color(255, 255, 255));
        lab6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab6.setText("0");
        lab6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lab4.setBackground(new java.awt.Color(255, 51, 51));
        lab4.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab4.setForeground(new java.awt.Color(255, 255, 255));
        lab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab4.setText("0");
        lab4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lab5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lab6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lab7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        lab1.setBackground(new java.awt.Color(255, 255, 255));
        lab1.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab1.setText("0");
        lab1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lab2.setBackground(new java.awt.Color(255, 51, 51));
        lab2.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab2.setText("0");
        lab2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lab3.setBackground(new java.awt.Color(255, 51, 51));
        lab3.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab3.setForeground(new java.awt.Color(255, 255, 255));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3.setText("0");
        lab3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lab3.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lab8.setBackground(new java.awt.Color(255, 51, 51));
        lab8.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab8.setForeground(new java.awt.Color(255, 255, 255));
        lab8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab8.setText("0");
        lab8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lab9.setBackground(new java.awt.Color(255, 51, 51));
        lab9.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        lab9.setForeground(new java.awt.Color(255, 255, 255));
        lab9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab9.setText("0");
        lab9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        lab9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        _restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257)
                        .addComponent(_restart, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lab8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lab9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(336, 336, 336)
                                .addComponent(_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_restart, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lab9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__stopActionPerformed
        // TODO add your handling code here:
        set = true;
    }//GEN-LAST:event__stopActionPerformed

    private void _restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__restartActionPerformed
        // TODO add your handling code here:
        thread_run = false;
        t1.interrupt();
        restart();
    }//GEN-LAST:event__restartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _restart;
    private javax.swing.JButton _stop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel lab8;
    private javax.swing.JLabel lab9;
    // End of variables declaration//GEN-END:variables
}
